{% set name = "detectree" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/detectree-{{ version }}.tar.gz
  sha256: d99d036188ac06cfadb9c5d67b1e47e67e11d90572e3bbce7eca004ba5e3e7dc

build:
  entry_points:
    - detectree = detectree.cli.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - dask-core
    - huggingface_hub
    - joblib
    - laspy >=2.0.0
    - lightgbm
    - numpy >=1.15
    - opencv >=4.0.0
    - pandas >=0.23
    - pymaxflow >=1.0.0
    - rasterio >=1.0.0
    - scikit-image >=0.25.0
    - scikit-learn
    - scipy >=1.0.0
    - skops
    - shapely
    - tqdm

test:
  imports:
    - detectree
    - detectree.cli
  commands:
    - pip check
    - detectree --help
  requires:
    - pip
    - opencv =*=headless*
    - python >=3.10

about:
  home: https://github.com/martibosch/detectree
  summary: Tree detection from aerial imagery in Python.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://detectree.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - martibosch
