{% set name = "detectree" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/detectree-{{ version }}.tar.gz
  sha256: 6b8d5e5a1e7f628a8ec022702dbd713de8572029a1a327a99db3ac6f71f6ade8

build:
  entry_points:
    - detectree = detectree.cli.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - dask-core
    - joblib
    - laspy >=2.0.0
    - lightgbm
    - numpy >=1.15
    - opencv >=4.0.0
    - pandas >=0.23
    - pymaxflow >=1.0.0
    - rasterio >=1.0.0
    - scikit-image
    - scikit-learn
    - scipy >=1.0.0
    - skops
    - shapely
    - tqdm

test:
  imports:
    - detectree
    - detectree.cli
  commands:
    - pip check
    - detectree --help
  requires:
    - pip

about:
  home: https://github.com/martibosch/detectree
  summary: Tree detection from aerial imagery in Python.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://detectree.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - martibosch
