{% set name = "detectree" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/detectree-{{ version }}.tar.gz
  sha256: f308c8e82e9b5a28728f484cb798af4623c51cd350f0684afb97b370d91a0f8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - detectree=detectree.cli.main:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - dask-core
    - joblib
    - laspy >=2.0.0
    - numpy >=1.15
    - pandas >=0.23
    - pillow
    - pymaxflow >=1.0.0
    - python >=3.6
    - rasterio >=1.0.0
    - scikit-image
    - scikit-learn
    - scipy >=1.0.0
    - shapely    
    - tqdm

test:
  imports:
    - detectree
    - detectree.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martibosch/detectree
  summary: Tree detection from aerial imagery
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://detectree.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - martibosch
